//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AilimitSaveResolver.ProgressTracker.Locales {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ItemsCommon {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ItemsCommon() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("AilimitSaveResolver.ProgressTracker.Locales.ItemsCommon", typeof(ItemsCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string 未强化 {
            get {
                return ResourceManager.GetString("未强化", resourceCulture);
            }
        }
        
        internal static string 等级1 {
            get {
                return ResourceManager.GetString("等级1", resourceCulture);
            }
        }
        
        internal static string 等级2 {
            get {
                return ResourceManager.GetString("等级2", resourceCulture);
            }
        }
        
        internal static string 等级3 {
            get {
                return ResourceManager.GetString("等级3", resourceCulture);
            }
        }
        
        internal static string 等级4 {
            get {
                return ResourceManager.GetString("等级4", resourceCulture);
            }
        }
        
        internal static string 等级5 {
            get {
                return ResourceManager.GetString("等级5", resourceCulture);
            }
        }
        
        internal static string 等级6 {
            get {
                return ResourceManager.GetString("等级6", resourceCulture);
            }
        }
        
        internal static string 等级7 {
            get {
                return ResourceManager.GetString("等级7", resourceCulture);
            }
        }
        
        internal static string 等级8 {
            get {
                return ResourceManager.GetString("等级8", resourceCulture);
            }
        }
        
        internal static string 等级9 {
            get {
                return ResourceManager.GetString("等级9", resourceCulture);
            }
        }
        
        internal static string 等级Max {
            get {
                return ResourceManager.GetString("等级Max", resourceCulture);
            }
        }
        
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        internal static string Collected {
            get {
                return ResourceManager.GetString("Collected", resourceCulture);
            }
        }
    }
}
